default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: attendance_sheet_collector_development

test:
  <<: *default
  database: attendance_sheet_collector_test

production:
  <<: *default
  database: attendance_sheet_collector
