default: &default
  adapter: postgresql
  encording: unicode 
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  
development:
  <<: *default
  database: attendance_sheet_collector_development

test:
  <<: *default
  database: attendance_sheet_collector_test

production:
  <<: *default
  database: attendance_sheet_collector
