default: &default
  adapter: postgresql
  encording: unicode 
  timeout: 5000
  host: DB_HOST
  username: DB_USERNAME
  password: DB_PASSWORD
  
development:
  <<: *default
  database: attendance_sheet_collector_development

test:
  <<: *default
  database: attendance_sheet_collector_test

production:
  <<: *default
  database: attendance_sheet_collector
